# Generated by Django 5.0.4 on 2026-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_veterinarian_zookeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zookeeper',
            old_name='managed_animal',
            new_name='managed_animals',
        ),
    ]
