# Generated by Django 5.0.4 on 2026-07-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Yoga', 'Yoga'), ('Crossfit', 'Crossfit'), ('Calisthenics', 'Calisthenics')], max_length=20),
        ),
    ]
