# Generated by Django 5.0.4 on 2026-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
    ]
