# Generated by Django 5.0.4 on 2026-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('photo', models.URLField()),
                ('birth_date', models.DateField()),
                ('works_full_time', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(choices=[('Sf', 'Sofia'), ('Pd', 'Plovdiv'), ('V', 'Varna'), ('Bs', 'Burgas')], max_length=20)),
            ],
        ),
    ]
