# Generated by Django 5.0.4 on 2026-06-30 19:03

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    #SELECT * FROM shoe;
    # shoes = ShoeModel.objects.all|()
    # print({s.brand for s in shoes})

    # SELECT DISTINCT brand FROM shoe
    # Optimization
    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    # for b in unique_brands:
    #     brand = UniqueBrandsModel(brand=b)
    #     brand.save()  # INSERT ONLY ONE ROW

    # Optimization
    unique_brands_to_create = [UniqueBrandsModel(brand_name=b) for b in unique_brands]
    UniqueBrandsModel.objects.bulk_create(unique_brands_to_create) # INSERT multiple records at once


# Create reversed function
def reverse_create_unique_brands(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.all().delete() # DELETE FROM unique_brands;



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        )
    ]
