# Generated by Django 5.0.4 on 2026-07-01 10:08

from django.db import migrations


def create_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    # Research F objects
    for person in PersonModel.objects.all(): # [Object(1), Object(2)]
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"

        person.save()


def reverse_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    default_field = PersonModel._meta.get_field('age_group').default

    # Research bulk_update
    for p in PersonModel.objects.all():
        p.age_group = default_field
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(
            code=create_age_group,
            reverse_code=reverse_age_group
        ),
    ]
