# Generated by Django 5.0.4 on 2026-07-02 05:29

from django.db import migrations
from django.db.models import Model

from main_app.models import Item


def set_rarity_item(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')

    for item in ItemModel.objects.all():
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        elif item.price >= 31:
            item.rarity = "Mega Rare"
        item.save()


def reverse_item_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    default_value = ItemModel._meta.get_field('rarity').default

    for item in ItemModel.objects.all():
        item.rarity = default_value
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_rarity_item,
            reverse_code=reverse_item_rarity
        )
    ]
