# Generated by Django 5.0.4 on 2026-07-02 06:37

from django.db import migrations


MULTIPLIER: int = 120
PRICE_THRESHOLD: int = 750


def set_price(apps, schema_editor):
    SmarthphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmarthphoneModel.objects.all():
        phone.price = len(phone.brand) * MULTIPLIER
        phone.save()


def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmartphoneModel.objects.all():
        if phone.price >= PRICE_THRESHOLD:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"
        phone.save()

def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_fields_set(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_price = SmartphoneModel._meta.get_field('price').default
    default_category = SmartphoneModel._meta.get_field('category').default

    for phone in SmartphoneModel.objects.all():
        phone.price = default_price
        phone.category = default_category
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_price_and_category,
            reverse_code=reverse_fields_set
        )
    ]
