# Generated by Django 5.0.4 on 2026-07-02 07:44
from datetime import timedelta

from django.db import migrations


def set_fields(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    for order in OrderModel.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'Cancelled':
            order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(
            code=set_fields
        )
    ]
