# Generated by Django 5.0.4 on 2026-07-19 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_studentenrollment_alter_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='enrollment_dat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
