# Generated by Django 5.0.4 on 2026-07-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='car_number',
            new_name='card_number',
        ),
    ]
